FROM postgres:13.4-alpine
ENV LANG ja_JP.utf8R
ENV POSTGIS_MAJOR 3.2
ENV POSTGIS_VERSION PostGIS3.2.0alpha1
RUN apt-get update \
  && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
  && apt-get install -y --no-install-recommends \
  postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
  postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \
  postgis=$POSTGIS_VERSION \
  && rm -rf /var/lib/apt/lists/*
EXPOSE 5433
